version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  jobs:
    post_install:
      - echo ${testitest}
sphinx:
  fail_on_warning: true
  
formats:
  - pdf
  - epub

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
